apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerRegistry.secretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\"}}}" .Values.dockerRegistry.registry .Values.dockerRegistry.username .Values.dockerRegistry.password .Values.dockerRegistry.email | b64enc }}
